Repository CNUOSS/CNU-SAM-BE, pull requests merged in 2022-06, with the labels that each got.

#96 2.2.4 수업 SW 상세 조회
  src/main/java/gp/cnusambe/controller/LectureSWController.java
  src/main/java/gp/cnusambe/service/LectureSWService.java
Labels: enhancement

#97 [#90] 분석결과에 license없이 Version 등록 가능한 기능 구현
  src/main/java/gp/cnusambe/controller/VersionController.java
  src/main/java/gp/cnusambe/domain/OssAnalysisMap.java
  src/main/java/gp/cnusambe/service/VersionService.java
Labels: bug, enhancement

#104 Add license as Column In LectureSW
  src/main/java/gp/cnusambe/domain/LectureMap.java
  src/main/java/gp/cnusambe/domain/LectureSW.java
  src/main/java/gp/cnusambe/domain/LectureSWList.java
  src/main/java/gp/cnusambe/domain/SWInLectureSW.java
  src/main/java/gp/cnusambe/dto/SWInLectureSWDto.java
  src/main/java/gp/cnusambe/service/LectureSWService.java
Labels: bug, enhancement

#106 Fix Id Mapping Error in SW
  src/main/java/gp/cnusambe/controller/LectureSWController.java
  src/main/java/gp/cnusambe/controller/RegistrationSWController.java
  src/main/java/gp/cnusambe/controller/SubscriptionSWController.java
  src/main/java/gp/cnusambe/service/LectureSWService.java
  src/main/java/gp/cnusambe/service/RegistrationSWService.java
  src/main/java/gp/cnusambe/service/SubscriptionSWService.java
Labels: bug
