Repository CNUOSS/CNU-SAM-BE, pull requests merged in 2022-05, with the labels that each got.

#8 [#2 #3 #4 #5] 회원 가입, 로그인, 로그아웃, 토큰 리프레쉬, 리로드 기능 구현
  .github/PULL_REQUEST_TEMPLATE.md
  build.gradle
  src/main/java/gp/cnusambe/config/WebSecurityConfig.java
  src/main/java/gp/cnusambe/controller/UserController.java
  src/main/java/gp/cnusambe/domain/User.java
  src/main/java/gp/cnusambe/exception/AccessTokenException.java
  src/main/java/gp/cnusambe/exception/InvalidPasswordException.java
  src/main/java/gp/cnusambe/exception/RefreshTokenException.java
  src/main/java/gp/cnusambe/exception/UserNotFoundException.java
  src/main/java/gp/cnusambe/payload/request/LoginRequest.java
  src/main/java/gp/cnusambe/payload/request/LogoutOrRefreshRequest.java
  src/main/java/gp/cnusambe/payload/request/SignupRequest.java
  src/main/java/gp/cnusambe/payload/response/ErrorResponse.java
  src/main/java/gp/cnusambe/payload/response/LoginResponse.java
  src/main/java/gp/cnusambe/payload/response/UserInfoResponse.java
  src/main/java/gp/cnusambe/repository/UserRepository.java
  src/main/java/gp/cnusambe/security/JwtAccessDeniedHandler.java
  src/main/java/gp/cnusambe/security/JwtAuthEntryPoint.java
  src/main/java/gp/cnusambe/security/JwtAuthFilter.java
  src/main/java/gp/cnusambe/security/JwtTokenProvider.java
  src/main/java/gp/cnusambe/security/UserDetailsImpl.java
  src/main/java/gp/cnusambe/service/UserDetailsServiceImpl.java
  src/main/java/gp/cnusambe/service/UserService.java
  src/main/java/gp/cnusambe/util/RedisUtil.java
  src/main/resources/application.properties
  src/test/java/gp/cnusambe/controller/UserControllerTest.java
Labels: enhancement

#12 [#1] 3.3.2 License 등록하기 코드 refactor, 테스트 코드
  build.gradle
  src/main/java/gp/cnusambe/config/AppConfig.java
  src/main/java/gp/cnusambe/controller/OssLicenseController.java
  src/main/java/gp/cnusambe/domain/LicenseRestrictionMap.java
  src/main/java/gp/cnusambe/domain/OssLicense.java
  src/main/java/gp/cnusambe/domain/Restriction.java
  src/main/java/gp/cnusambe/dto/OssLicenseDto.java
  src/main/java/gp/cnusambe/service/LicenseRestrictionMapService.java
  src/main/java/gp/cnusambe/service/OssLicenseService.java
  src/main/resources/application.properties
  src/test/java/gp/cnusambe/controller/OssLicenseControllerTest.java
  src/test/java/gp/cnusambe/service/OssLicenseServiceTest.java
Labels: refactror

#16 [#14]3.3.3 License 삭제하기
  src/main/java/gp/cnusambe/controller/OssLicenseController.java
  src/main/java/gp/cnusambe/domain/LicenseRestrictionMap.java
  src/main/java/gp/cnusambe/domain/OssLicense.java
  src/main/java/gp/cnusambe/repository/LicenseRestrictionMapRepository.java
  src/main/java/gp/cnusambe/repository/OssLicenseRepository.java
  src/main/java/gp/cnusambe/service/OssLicenseService.java
  src/test/java/gp/cnusambe/controller/OssLicenseControllerTest.java
Labels: enhancement

#33 [#30]3.4.3 Restriction name Data
  src/main/java/gp/cnusambe/controller/RestrictionController.java
  src/main/java/gp/cnusambe/repository/RestrictionRepository.java
  src/main/java/gp/cnusambe/service/RestrictionService.java
Labels: enhancement

#34 [#31] 3.4.4 License Type name Data 가져오기
  src/main/java/gp/cnusambe/controller/OssLicenseTypeController.java
  src/main/java/gp/cnusambe/repository/OssLicenseTypeRepository.java
  src/main/java/gp/cnusambe/service/OssLicenseTypeService.java
Labels: enhancement

#38 [#27] OssLicense 삭제기능 오류 해결
  src/main/java/gp/cnusambe/service/OssLicenseService.java
Labels: bug

#39 [#24] 구독 SW 등록
  src/main/java/gp/cnusambe/controller/LectureSWController.java
  src/main/java/gp/cnusambe/controller/SubscriptionSWController.java
  src/main/java/gp/cnusambe/domain/SubscriptionSW.java
  src/main/java/gp/cnusambe/exception/custom/SWNotFoundException.java
  src/main/java/gp/cnusambe/payload/request/SubscriptionSWRequest.java
  src/main/java/gp/cnusambe/payload/response/SubscriptionSWResponse.java
  src/main/java/gp/cnusambe/repository/SubscriptionSWRepository.java
  src/main/java/gp/cnusambe/service/LectureSWService.java
  src/main/java/gp/cnusambe/service/SubscriptionSWService.java
Labels: enhancement

#40 [#22 #23] 이수 구분 & 조직 분류 전체 조회 : 데이터 타입 수정
  src/main/java/gp/cnusambe/controller/LectureSWController.java
  src/main/java/gp/cnusambe/payload/response/DepartmentResponse.java
  src/main/java/gp/cnusambe/payload/response/LectureTypeResponse.java
  src/main/java/gp/cnusambe/service/LectureSWService.java
Labels: refactror

#44 [#42] ProjectDto, OssLicenseDto -> Response, Request Dto로 변경하기
  src/main/java/gp/cnusambe/controller/ProjectController.java
  src/main/java/gp/cnusambe/payload/request/ProjectPostRequest.java
  src/main/java/gp/cnusambe/payload/response/ProjectDetailResponse.java
  src/main/java/gp/cnusambe/payload/response/ProjectPostResponse.java
  src/main/java/gp/cnusambe/service/ProjectService.java
Labels: refactror

#51 [#47] 3.1.5 Project 삭제기능 구현
  src/main/java/gp/cnusambe/controller/ProjectController.java
  src/main/java/gp/cnusambe/service/ProjectService.java
Labels: enhancement

#61 [#29] 3.4.2 Category name Data 조회기능 구현
  src/main/java/gp/cnusambe/controller/ProjectCategoryController.java
  src/main/java/gp/cnusambe/service/ProjectCategoryService.java
Labels: enhancement

#66 [#64] Project 등록시 ProjectStatus -> "C"로 고정
  src/main/java/gp/cnusambe/payload/request/ProjectPostRequest.java
  src/test/java/gp/cnusambe/service/ProjectServiceTest.java
Labels: refactror

#72 [#55] 2.3.6 수업 등록용 SW 삭제
  src/main/java/gp/cnusambe/controller/RegistrationSWController.java
  src/main/java/gp/cnusambe/service/RegistrationSWService.java
Labels: enhancement

#76 SW : 계층에서 사용하는 데이터 구분하기
  src/main/java/gp/cnusambe/controller/RegistrationSWController.java
  src/main/java/gp/cnusambe/controller/SubscriptionSWController.java
  src/main/java/gp/cnusambe/domain/RegistrationSW.java
  src/main/java/gp/cnusambe/domain/SubscriptionSW.java
  src/main/java/gp/cnusambe/dto/RegistrationSWDto.java
  src/main/java/gp/cnusambe/service/RegistrationSWService.java
  src/main/java/gp/cnusambe/service/SubscriptionSWService.java
Labels: refactror

#80 [#75] OssLicenseListResponse : meta -> pageInfo로 변경
  src/main/java/gp/cnusambe/payload/response/OssLicenseListResponse.java
Labels: refactror

#83 [#82] 문자열인 user_id를 주어지면 project 등록이 안되는 오류 해결
  src/main/java/gp/cnusambe/config/AppConfig.java
  src/main/java/gp/cnusambe/payload/request/ProjectPostRequest.java
  src/main/java/gp/cnusambe/service/ProjectService.java
Labels: bug

#84 [#19] 3.2.5 Version 삭제 기능 구현
  src/main/java/gp/cnusambe/controller/VersionController.java
  src/main/java/gp/cnusambe/repository/AnalysisRestrictionMapRepository.java
  src/main/java/gp/cnusambe/repository/OssAnalysisMapRepository.java
  src/main/java/gp/cnusambe/service/VersionService.java
Labels: enhancement

#89 등록용 SW와 수업용 SW를 조인 테이블로 연결
  src/main/java/gp/cnusambe/controller/LectureSWController.java
  src/main/java/gp/cnusambe/domain/LectureMap.java
  src/main/java/gp/cnusambe/domain/LectureSW.java
  src/main/java/gp/cnusambe/dto/LectureMapDto.java
  src/main/java/gp/cnusambe/dto/LectureSWDto.java
  src/main/java/gp/cnusambe/dto/SWInLectureSWDto.java
  src/main/java/gp/cnusambe/payload/response/LectureSWResponse.java
  src/main/java/gp/cnusambe/repository/LectureMapRepository.java
  src/main/java/gp/cnusambe/repository/RegistrationSWRepository.java
  src/main/java/gp/cnusambe/service/LectureSWService.java
Labels: refactror
